
# Makefile for multiple source files

# Make executable file called rubiks
problem599: rubix.c
	mpicc rubix.c -o problem599

# Make executable file called rectangle
problem85: rectangle.c
	mpicc rectangle.c -o problem85 -lm
